name: iac-security-pipeline
on: [push]
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Quality Gate Checkov Scan
        run: |
          pip3 install checkov
          checkov -d . --framework terraform
